update=5/24/2016 1:29:00 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=sensor-water-rescue
LibName2=power
LibName3=device
LibName4=transistors
LibName5=conn
LibName6=linear
LibName7=regul
LibName8=74xx
LibName9=cmos4000
LibName10=adc-dac
LibName11=memory
LibName12=xilinx
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName32=C:/Program Files/KiCad/share/kicad/library/74xx
LibName33=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName34=C:/Program Files/KiCad/share/kicad/library/actel
LibName35=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName36=C:/Program Files/KiCad/share/kicad/library/Altera
LibName37=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName38=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName39=C:/Program Files/KiCad/share/kicad/library/atmel
LibName40=C:/Program Files/KiCad/share/kicad/library/audio
LibName41=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName42=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName43=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName44=C:/Program Files/KiCad/share/kicad/library/conn
LibName45=C:/Program Files/KiCad/share/kicad/library/contrib
LibName46=C:/Program Files/KiCad/share/kicad/library/cypress
LibName47=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName48=C:/Program Files/KiCad/share/kicad/library/device
LibName49=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName50=C:/Program Files/KiCad/share/kicad/library/diode
LibName51=C:/Program Files/KiCad/share/kicad/library/display
LibName52=C:/Program Files/KiCad/share/kicad/library/dsp
LibName53=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName54=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName55=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName56=C:/Program Files/KiCad/share/kicad/library/gennum
LibName57=C:/Program Files/KiCad/share/kicad/library/graphic
LibName58=C:/Program Files/KiCad/share/kicad/library/hc11
LibName59=C:/Program Files/KiCad/share/kicad/library/intel
LibName60=C:/Program Files/KiCad/share/kicad/library/interface
LibName61=C:/Program Files/KiCad/share/kicad/library/ir
LibName62=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName63=C:/Program Files/KiCad/share/kicad/library/linear
LibName64=C:/Program Files/KiCad/share/kicad/library/logo
LibName65=C:/Program Files/KiCad/share/kicad/library/maxim
LibName66=C:/Program Files/KiCad/share/kicad/library/memory
LibName67=C:/Program Files/KiCad/share/kicad/library/microchip
LibName68=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName69=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName70=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName71=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName72=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName73=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName74=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName75=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName76=C:/Program Files/KiCad/share/kicad/library/motorola
LibName77=C:/Program Files/KiCad/share/kicad/library/msp430
LibName78=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName79=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName80=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName81=C:/Program Files/KiCad/share/kicad/library/opto
LibName82=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName83=C:/Program Files/KiCad/share/kicad/library/philips
LibName84=C:/Program Files/KiCad/share/kicad/library/power
LibName85=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName86=C:/Program Files/KiCad/share/kicad/library/powerint
LibName87=C:/Program Files/KiCad/share/kicad/library/pspice
LibName88=C:/Program Files/KiCad/share/kicad/library/references
LibName89=C:/Program Files/KiCad/share/kicad/library/regul
LibName90=C:/Program Files/KiCad/share/kicad/library/relays
LibName91=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName92=C:/Program Files/KiCad/share/kicad/library/sensors
LibName93=C:/Program Files/KiCad/share/kicad/library/silabs
LibName94=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName95=C:/Program Files/KiCad/share/kicad/library/stm8
LibName96=C:/Program Files/KiCad/share/kicad/library/stm32
LibName97=C:/Program Files/KiCad/share/kicad/library/supertex
LibName98=C:/Program Files/KiCad/share/kicad/library/switches
LibName99=C:/Program Files/KiCad/share/kicad/library/texas
LibName100=C:/Program Files/KiCad/share/kicad/library/transf
LibName101=C:/Program Files/KiCad/share/kicad/library/transistors
LibName102=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName103=C:/Program Files/KiCad/share/kicad/library/valves
LibName104=C:/Program Files/KiCad/share/kicad/library/video
LibName105=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName106=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName107=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName108=sensor-water-cache
LibName109=kicad-library/library/74xgxx
LibName110=kicad-library/library/74xx
LibName111=kicad-library/library/ac-dc
LibName112=kicad-library/library/actel
LibName113=kicad-library/library/adc-dac
LibName114=kicad-library/library/Altera
LibName115=kicad-library/library/analog_devices
LibName116=kicad-library/library/analog_switches
LibName117=kicad-library/library/atmel
LibName118=kicad-library/library/audio
LibName119=kicad-library/library/battery_management
LibName120=kicad-library/library/bbd
LibName121=kicad-library/library/brooktre
LibName122=kicad-library/library/cmos_ieee
LibName123=kicad-library/library/cmos4000
LibName124=kicad-library/library/conn
LibName125=kicad-library/library/contrib
LibName126=kicad-library/library/Currawong
LibName127=kicad-library/library/cypress
LibName128=kicad-library/library/dc-dc
LibName129=kicad-library/library/device
LibName130=kicad-library/library/digital-audio
LibName131=kicad-library/library/diode
LibName132=kicad-library/library/display
LibName133=kicad-library/library/dsp
LibName134=kicad-library/library/elec-unifil
LibName135=kicad-library/library/ESD_Protection
LibName136=kicad-library/library/ftdi
LibName137=kicad-library/library/gennum
LibName138=kicad-library/library/graphic
LibName139=kicad-library/library/hc11
LibName140=kicad-library/library/intel
LibName141=kicad-library/library/interface
LibName142=kicad-library/library/ir
LibName143=kicad-library/library/Lattice
LibName144=kicad-library/library/linear
LibName145=kicad-library/library/logo
LibName146=kicad-library/library/maxim
LibName147=kicad-library/library/memory
LibName148=kicad-library/library/microchip
LibName149=kicad-library/library/microchip_dspic33dsc
LibName150=kicad-library/library/microchip_pic10mcu
LibName151=kicad-library/library/microchip_pic12mcu
LibName152=kicad-library/library/microchip_pic16mcu
LibName153=kicad-library/library/microchip_pic18mcu
LibName154=kicad-library/library/microchip_pic32mcu
LibName155=kicad-library/library/microcontrollers
LibName156=kicad-library/library/motor_drivers
LibName157=kicad-library/library/motorola
LibName158=kicad-library/library/msp430
LibName159=kicad-library/library/nordicsemi
LibName160=kicad-library/library/nxp_armmcu
LibName161=kicad-library/library/onsemi
LibName162=kicad-library/library/opto
LibName163=kicad-library/library/Oscillators
LibName164=kicad-library/library/philips
LibName165=kicad-library/library/power
LibName166=kicad-library/library/Power_Management
LibName167=kicad-library/library/powerint
LibName168=kicad-library/library/pspice
LibName169=kicad-library/library/references
LibName170=kicad-library/library/regul
LibName171=kicad-library/library/relays
LibName172=kicad-library/library/rfcom
LibName173=kicad-library/library/sensors
LibName174=kicad-library/library/silabs
LibName175=kicad-library/library/siliconi
LibName176=kicad-library/library/stm8
LibName177=kicad-library/library/stm32
LibName178=kicad-library/library/supertex
LibName179=kicad-library/library/switches
LibName180=kicad-library/library/texas
LibName181=kicad-library/library/transf
LibName182=kicad-library/library/transistors
LibName183=kicad-library/library/ttl_ieee
LibName184=kicad-library/library/valves
LibName185=kicad-library/library/video
LibName186=kicad-library/library/Worldsemi
LibName187=kicad-library/library/Xicor
LibName188=kicad-library/library/xilinx
LibName189=kicad-library/library/Zilog
LibName190=kicad-library/library/A-KHANH/power-6V5
LibName191=kicad-library/library/A-KHANH/power -6v5
